### ISSUE TITLE
Create PHP Unit Tests

### ISSUE THREAD

**Issue by develth** [raphbibus/substance-php-sdk#1]
Hey there, 

create some PHP Unit tests to ensure code quality & stability. 
Combine it with e.g. scrutinizer-ci.com / https://travis-ci.org

**Comment by ralphcibis-thomann** [comment]
- add test tenant
- add test credentials

**Comment by ralphcibis-thomann** [comment]
Added manual PHP unit tests for now. CI will follow some time later.
