### ISSUE TITLE
Let Substance just handle Auth and Substance Connections

### ISSUE THREAD

**Issue by develth** [raphbibus/substance-php-sdk#3]
Split a .e.g. 

    $updatedBeacon = $substance->connectContent($beacon,"https://www.rakete7.com","Rakete 7 Website","Hab ich mit dem SDK erstellt!");
 
Into e.g.

    $contentConnection = new ContentConnection($beacon, $url, $title, $desc);
    //maybe do other stuff with the $contentConnection
    $substance->connectContent($contentConnection);

Or much better:

    $content = new Content($url, $title, $desc);
    $beaconContent = new ContentConnection($beacon, $content);
    $substance->connectContent($beaconContent);

Also possible that each of the mentioned functions is working. 
With this setup the SDK users are much more flexible with handle and generate content.

**Comment by ralphcibis-thomann** [comment]
changed structure to:
```php
$content = new Content("https://www.rakete7.com","Rakete 7 Website","Hab ich mit dem SDK erstellt!");

$contentConnection = new ContentConnection($beacon,$content);

$updatedBeacon = $substance->connectContent($contentConnection);
```
